---
title: Posgrados Instituto de Física
timezone: America/Bogota
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Universidad de Antioquia
email: posgrados@gfif.udea.edu.co
baseurl: "http://fisica.udea.edu.co"
admision: "/admision"
indicador: "/indicador"
contacto: "/contacto"
url: "http://fisica.udea.edu.co"
exclude:
- config.ru
- Gemfile
- Gemfile.lock
- vendor
- Procfile
- Rakefile
- TODO.md
include:
- _pages
categories:
- pregrado
- posgrado
- personal
- curso
- servicio
favicon: "/images/favicon.png"
twitter_username: PosgradosUdeA
fb_username: PosgradosUdeAntioquia
permalink: post/:year/:month/:day/:title
markdown: kramdown
authors:
  Posgrados Instituto de Física:
    display_name: Facultad de Ciencias Exactas y Naturales
    email: posgrados@gfif.udea.edu.co
    fb: PosgradosFisicaUdeA
    twitter: PosgradosUdeA
